function writeply(voxel, color, filename)
    file = fopen(filename,'w');    
    text = sprintf(['ply\n' ...
                    'format ascii 1.0\n' ...
                    'element vertex %s\n' ...
                    'property float x\n' ...
                    'property float y\n' ...
                    'property float z\n' ...
                    'property uchar red\n' ...
                    'property uchar green\n' ...
                    'property uchar blue\n' ...
                    'element face 0\n'...
                    'end_header\n'], num2str(size(voxel,1)));%write the data as ply text
     fprintf(file, text);    
     data = [voxel round(color)];
     dlmwrite(filename,num2str(data),'-append','delimiter','')    
     fclose(file);
end